<a href="https://colab.research.google.com/github/roseann47625/BSIS-2A-CABANG-ROSE-ANN-E/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
array = np.array([1,2,3])

In [9]:
# prompt: print(array)

print(array)


[1 2 3]


In [3]:
median = np.median(array)

In [8]:
# prompt: print(array)
print( array)

[1 2 3]


In [4]:
std_dev = np.std(array)


In [10]:
# prompt: print(array)
print(array)

[1 2 3]


In [5]:
total = np.sum ( array)

In [11]:
# prompt: print (array)
print(array)

[1 2 3]


In [6]:
reshaped_array = array.reshape((3,1))


In [12]:
# prompt: print(array)
print(array)

[1 2 3]


In [7]:
array1 = np.array([ 1, 2, 3])
array2 = np.array([4, 5, 6])
concatenated = np.concatenate((array1, array2))

In [13]:
# prompt: print(array)
print(array)

[1 2 3]


In [ ]:
numbers = np linespace ( 0,10,5)

In [14]:
# prompt: print(array)
print(array)

[1 2 3]


In [15]:
range_array= np.arange(0,10,2)

In [16]:
# prompt: print(array)
print(array)

[1 2 3]
